API_TIMEOUT = 15
POLLING_INTERVAL = 2
ORDERS_UPDATE_INTERVAL = 6
PRICE_UPDATE_INTERVAL = 5
BALANCE_UPDATE_INTERVAL = 60
HISTORY_UPDATE_INTERVAL = 70
TOKEN_REFRESH_INTERVAL = 900
LEVERAGE = 77
LOG_RETENTION_DAYS = 30
DATABASE_NAME = "terminal.db"

HISTORY_ORDERS_LIMIT = 20
